apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dry-run-secret
spec:
  encryptedData:
    password: AgCs5qDqvfSWS6IUUgelPRkCgDAvIyHgsSTLYDcQvER4p3Vl/+76l0cLSgk0N7gnX1WwzMZKO/tNfg4UN1NEPJsY2ZK/Lpr0BuQHE94HEzbiqN4tJUBz6HmbyDTrkST+/G2z4tPXE9GA3S6nxZ1VPPFogFbSYQV6ANqyy3FNChuIOCKvj+bBZdie4dj75FUqrpNEtLIgG8wt1V8j+0OJ6Wh9+YFdpzZUV6Kc+F4ghcbgSSbOna2Abv5ixJIpWhauRtmd1zqZbnpNQKsox/PeNWMH+4tYW9qc7YyfWPuwiGPtZzzVhKp6QzsUF7S5m7ZS7pXLn41j1BYvfoTXjv+ipZmSCnTFpskEvc8i8N9l09B+vz5MsobuZuIOSuiah0dklw0tfy8WiAz7YITz09H+isJq19py2DrwmygYOhj0tB2t+YUmg/TEyYvZItR9Dt4JbznYCTdXjL/y7XDYShFaFuMgd+gpMPGffq40uO5fLOcLA7zCf2uwUg4HVbH/RYZgJDmNHFF+gIMr/dMRifqsqDvsAUJ9lPY1Pv9rMuXYIaaSpydxQD0ecMy3HJ3h6wMgLtWgC44conTsvfqOrD2jpXUF95g+KXLzHb2fcXhv0JORCCBO0e+WhQMjdH4qZYRBRfeSZKgSHlgZciIYqSxx1FzDsf61IrbMcoNBNZMKGZWwF56sbUTqH4C79kDlj8QH7zVfM9g6pZKmx+fOWA==
    username: AgDHlS1C8K+q5Gt8EG+/GGvgVVclxCbbdYP27uBJXnXQwo53fKf7pA2uNNC/VpsovR5JWOOVfKu1mrb56YYJsv+Q6OuUpWNtkiY+6CsXTU4+9RuPts+v2uiAvonie3atkpiS6x/tjeV+Sl+xIeCPkq3DbXw3RUHzkkmEARi38F7KiglS2zhDnD3IkdTzUi5f1leaJPDxbaEgn9XBhXhc8gLa5WTrF1n3p4I77THuEgV+SiZjL385PI7N3vwU+Ku2y6oVToRxW8aGm7T7JY7fLj3Hv+uLw9f/MEBZ1SjMWIcWpSReFU+8W3bqQqfCRoYUw2lVKrQXIHXlz3gIliHhWIR0fNEX2yP8VqF5AqM5AWlBKIioSbPu6W1JAdZDNb8XwxgIZQzCKBE0wch1IUJiS4PO4q+yRjD7XGDffH/n5O4tuCkFjt/gzLLX2z1Kflp+X/i/m3Ya+lq7IeSPCIzNZ7O1JBWCkscYlX4Eb7Y+kcmjx7nYeSK21BynDc95MFxJxS+5DkBfjTnRcaI/HXYkWU0AqLig6aiZWh5mysKbuGM0G0Urf0ir/8skySPZgdIJdkG4BdMWfjBmiC/dY5AwrAx/yEfer7hO2T9qXODBNaXFmwrSGZEgc1QU/S1yKnSCrEV6cwlvcnHGkWO4Skv+K0eMQHLGo9TSHAjrEmRap0tSntHwF7Dks3Xswc8W1hCAji6mxym4K+ZspIXCOlm8xQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dry-run-secret

